const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs'), os = require('node:os'), path = require('node:path'), crypto = require('node:crypto');
const { start } = require('../test-support/server');
const { seed } = require('../test-support/review-fixture');
test('decision, outbox and isolated invitation commit together; replay and restart do not duplicate; onboarding is private', { timeout: 180000 }, async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'applicant-flow-')), file = path.join(dir, 'store.json');
  const { tokens } = seed(file, 0), secret = 'z'.repeat(48);
  const env = { ALPHAWAY_DATA_FILE: file, ALPHAWAY_ACCOUNT_AUTH: 'true', ALPHAWAY_SESSION_SECRET: secret };
  let app = await start(env);
  t.after(async () => { await app.stop(); fs.rmSync(dir, { recursive: true, force: true }); });
  const headers = { 'content-type': 'application/json', cookie: `alphaway_account=${tokens['user-admin']}` };
  const route = '/api/intakes/legacy-carrier';
  const post = (url, body, h = headers) => fetch(app.url + url, { method: 'POST', headers: h, body: JSON.stringify(body) });
  let version = 1;
  const change = async body => {
    const r = await post(route + '/review', { version, requestId: crypto.randomUUID(), ...body });
    const data = await r.json(); assert.equal(r.status, 200, JSON.stringify(data)); version = data.review.version; return data;
  };
  await change({ action: 'assign', assigneeId: 'user-admin' });
  for (const checkId of ['identity', 'authority', 'insurance', 'tax_form', 'agreement', 'service']) await change({ action: 'check', checkId, status: 'verified', evidence: 'Secure reviewed evidence' });
  const approval = { action: 'approve', version, requestId: crypto.randomUUID(), note: 'Private internal rationale', notifyApplicant: true, applicantMessage: 'Welcome. Please complete your onboarding.' };
  assert.equal((await post(route + '/review', { ...approval, applicantMessage: '' })).status, 400);
  assert.equal((await post(route + '/review', approval)).status, 200);
  assert.equal((await post(route + '/review', approval)).status, 200);
  let stored = JSON.parse(fs.readFileSync(file));
  assert.equal(stored.applicantOutbox.length, 1); assert.equal(stored.accounts.invitations.length, 1);
  const invite = stored.accounts.invitations[0];
  assert.notEqual(invite.companyId, 'alphaway');
  await app.stop(); app = await start(env);
  assert.equal((await fetch(app.url + route + '/workflow')).status, 401);
  const detail = await fetch(app.url + route + '/workflow', { headers }).then(r => r.json());
  assert.equal(detail.emails.length, 1); assert.equal(detail.configured, false); assert.equal(detail.workflow.ready, false);
  const token = crypto.createHmac('sha256', secret).update(`applicant-invitation:${invite.id}`).digest('hex');
  assert.equal((await post('/api/accounts/invitations/preview', { token }, { 'content-type': 'application/json' })).status, 200);
  const accept = await post('/api/accounts/accept', { token, name: 'Carrier owner', password: 'Local-test-password-123' }, { 'content-type': 'application/json' });
  assert.equal(accept.status, 201);
  const ownerHeaders = { cookie: accept.headers.get('set-cookie').split(';')[0] };
  const progress = await fetch(app.url + '/api/onboarding', { headers: ownerHeaders }).then(r => r.json());
  assert.equal(progress.onboarding.steps.account, true); assert.equal(progress.onboarding.ready, false);
  assert.equal((await fetch(app.url + '/api/operations', { headers: ownerHeaders })).status, 403);
  assert.equal((await fetch(app.url + '/api/app', { headers: ownerHeaders })).status, 403);
  assert.equal((await fetch(app.url + '/api/events', { headers: ownerHeaders })).status, 403);
  assert.equal((await post('/api/events', { type: 'booking.create', loadId: 'TEST' }, { ...ownerHeaders, 'content-type': 'application/json' })).status, 403);
  assert.equal(progress.onboarding.plan, 'dispatch-standard');
  assert.equal(progress.onboarding.truckCount, 2);
  assert.equal((await post('/api/stripe/checkout', { plan: 'dispatch-basic', truckCount: 1, billingMethod: 'weekly', termsVersion: require('../dispatch-plans').termsVersion }, { ...ownerHeaders, 'content-type': 'application/json' })).status, 400);
  assert.equal((await fetch(app.url + route + '/workflow', { headers: ownerHeaders })).status, 403);
  stored = JSON.parse(fs.readFileSync(file));
  assert.equal(stored.applicantOutbox[0].status, 'queued');
});
