const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { start } = require('../test-support/server');
const { seed } = require('../test-support/review-fixture');
const { termsVersion } = require('../dispatch-plans');
test('carrier screening persists, is staff-only, rejects stale changes and never grants service', { timeout: 180000 }, async t => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'carrier-checks-'));
  const file = path.join(dir, 'store.json');
  const { tokens } = seed(file, 0);
  let app = await start({ ALPHAWAY_DATA_FILE: file, ALPHAWAY_ACCOUNT_AUTH: 'true' });
  t.after(async () => { await app.stop(); fs.rmSync(dir, { recursive: true, force: true }); });
  const headers = role => ({ 'content-type': 'application/json', cookie: role ? `alphaway_account=${tokens[`user-${role}`]}` : '' });
  const post = (route, data, role = 'admin') => fetch(app.url + route, { method: 'POST', headers: headers(role), body: JSON.stringify(data) });
  const submitted = await post('/api/intakes', { type: 'carrier-onboarding', fields: { legal_carrier_name: 'TEST ONLY carrier', primary_contact: 'TEST contact', business_email: 'test@example.com', dot_number: '000000', mc_number: '000000', dispatch_package: 'dispatch-standard', billing_method: 'weekly', dispatch_terms: termsVersion, available_units: '1' } }, '');
  assert.equal(submitted.status, 201);
  const { intake } = await submitted.json();
  assert.equal(intake.automation, undefined, 'private report is not returned to anonymous submitter');
  const route = `/api/intakes/${intake.id}`;
  const get = () => fetch(app.url + route, { headers: headers('admin') }).then(r => r.json());
  const first = await get();
  assert.equal(first.review.automation.checks.identifiers.status, 'needs_review');
  for (const role of ['', 'driver', 'carrier-owner', 'broker', 'shipper']) assert.ok([401, 403].includes((await post(route + '/verification', { version: 1 }, role)).status));
  assert.equal((await post(route + '/verification', { version: 0 })).status, 409);
  const updated = await (await post(route + '/verification', { version: 1 })).json();
  assert.equal(updated.review.version, 2);
  assert.equal(updated.review.status, 'received');
  assert.equal(updated.review.decision, null);
  assert.equal(updated.review.historyCount, 2);
  assert.equal((await post(route + '/review', { version: 2, requestId: 'forged-automation-123', action: 'automatic_checks', automation: { overall: 'passed' } })).status, 400);
  await app.stop(); app = await start({ ALPHAWAY_DATA_FILE: file, ALPHAWAY_ACCOUNT_AUTH: 'true' });
  assert.deepEqual((await get()).review.automation, updated.review.automation);
  const saved = JSON.parse(fs.readFileSync(file));
  assert.equal(saved.operations.billingSubscriptions.length, 0);
  assert.equal(saved.intakeReviews[intake.id].history[0].automation.checks.submission.status, 'needs_review');
});
