(() => {
 const loads=[
 {id:'HAR-1001',from:'Denver, CO',to:'Phoenix, AZ',equipment:'Dry Van',rate:'$2,540',miles:698,driver:'Marcus Lane',truck:'Unit 204',progress:62,speed:58,status:'In transit'},
 {id:'HAR-1002',from:'Colorado Springs, CO',to:'Dallas, TX',equipment:'Reefer',rate:'$3,185',miles:874,driver:'Daniela Ruiz',truck:'Unit 317',progress:12,speed:0,status:'At pickup'},
 {id:'HAR-1003',from:'Fort Collins, CO',to:'Kansas City, MO',equipment:'Flatbed',rate:'$2,950',miles:992,driver:'Casey Owens',truck:'Unit 278',progress:45,speed:55,status:'In transit'}
 ];
 const byId=id=>document.getElementById(id);if(!byId('hdLoads'))return;
 let selected=loads[0];
 function select(load){selected=load;byId('hdDriver').textContent=`${load.driver} · ${load.truck}`;byId('hdContact').textContent=load.driver;byId('hdRoute').textContent=`${load.from} → ${load.to}`;byId('hdOrigin').textContent=load.from;byId('hdDestination').textContent=load.to;byId('hdProgress').textContent=load.progress+'%';byId('hdSpeed').textContent=load.speed+' mph';byId('hdStatus').textContent=load.status;byId('hdTruck').style.left=load.progress+'%';byId('hdChat').replaceChildren();for(const [who,text] of [['Dispatch','Shipment details confirmed. Please share the next milestone.'],[load.driver,load.status==='At pickup'?'At the pickup appointment.':'Loaded and moving toward delivery.']]){const p=document.createElement('p'),b=document.createElement('strong');b.textContent=who+' ';p.append(b,document.createTextNode(text));byId('hdChat').append(p);}byId('hdMessageStatus').textContent='Sample conversation · No messages are sent.';document.querySelectorAll('[data-hd-load]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.hdLoad===load.id)));}
 function render(){const list=byId('hdLoads');list.replaceChildren();const matches=loads.filter(l=>byId('hdEquipment').value==='all'||l.equipment===byId('hdEquipment').value);for(const l of matches){const card=document.createElement('article');const tag=document.createElement('p');tag.className='kicker';tag.textContent=l.id+' · '+l.equipment;const h=document.createElement('h3');h.textContent=l.from+' → '+l.to;const detail=document.createElement('p');detail.textContent=l.rate+' · '+l.miles+' miles';const actions=document.createElement('div');actions.className='hd-actions';const button=document.createElement('button');button.type='button';button.textContent='View route & driver';button.dataset.hdLoad=l.id;button.setAttribute('aria-pressed',String(selected.id===l.id));button.addEventListener('click',()=>select(l));const signup=document.createElement('a');signup.href='/solutions-carriers.html';signup.textContent='Request access';actions.append(button,signup);card.append(tag,h,detail,actions);list.append(card);}if(!matches.some(l=>l.id===selected.id))select(matches[0]);}
 byId('hdEquipment').addEventListener('change',render);
 byId('hdMessage').addEventListener('click',()=>{const p=document.createElement('p');p.textContent=selected.driver+': Sample milestone update received.';byId('hdChat').append(p);while(byId('hdChat').children.length>3)byId('hdChat').firstChild.remove();byId('hdMessageStatus').textContent='Preview updated on this page only. Nothing was sent.';});
 render();select(selected);
})();
