import { PublicClientApplication } from '@azure/msal-browser';
import { aliases, isHarperMessage } from './inbox-filter';
const panel=document.getElementById('harperInbox');
const state=document.getElementById('inboxStatus'), list=document.getElementById('inboxMessages'), detail=document.getElementById('inboxMessage');
const connect=document.getElementById('inboxConnect'), refresh=document.getElementById('inboxRefresh'), older=document.getElementById('inboxOlder'), disconnect=document.getElementById('inboxDisconnect');
let app, account, epoch=0, busy=false, next=null, scanned=0, seen=new Set();
const scopes=['Mail.Read','User.Read'];
const first='https://graph.microsoft.com/v1.0/me/messages?$top=100&$orderby=receivedDateTime%20desc&$select=id,subject,from,toRecipients,ccRecipients,receivedDateTime,isRead';
async function admin(){const r=await fetch('/api/inbox/config',{cache:'no-store'});if(!r.ok)throw new Error('Sign in as administrator to use this inbox.');return r.json();}
async function init(){if(app)return app;const config=await admin();app=new PublicClientApplication({auth:{clientId:config.clientId,authority:'https://login.microsoftonline.com/consumers',redirectUri:location.origin+'/inbox-auth.html'},cache:{cacheLocation:'memoryStorage'}});await app.initialize();return app;}
function controls(){refresh.disabled=older.disabled=disconnect.disabled=!account||busy;older.hidden=!next;connect.disabled=busy;}
function reset(){epoch++;account=null;next=null;scanned=0;seen.clear();list.replaceChildren();detail.replaceChildren();controls();}
async function graph(url){await admin();const parsed=new URL(url);if(parsed.origin!=='https://graph.microsoft.com'||!parsed.pathname.startsWith('/v1.0/me'))throw new Error('Invalid mailbox request.');const token=await app.acquireTokenSilent({account,scopes});const r=await fetch(url,{headers:{Authorization:'Bearer '+token.accessToken,Prefer:'outlook.body-content-type="text"'}});if(!r.ok)throw new Error(r.status===429?'Microsoft is busy. Wait a minute and refresh.':'Microsoft could not load mail. Reconnect Outlook and try again.');return r.json();}
function sayError(e){state.textContent=e?.errorCode?'Microsoft sign-in needs attention ('+e.errorCode+'). Select Connect Outlook to try again.':e.message||'Unable to load the inbox.';}
async function openMessage(m){const version=epoch;try{const body=await graph('https://graph.microsoft.com/v1.0/me/messages/'+encodeURIComponent(m.id)+'?$select=subject,body,from,toRecipients,ccRecipients,replyTo');if(version!==epoch)return;if(!isHarperMessage(body))throw new Error('This message is not addressed to a Harper company address.');detail.replaceChildren();const h=document.createElement('h4');h.textContent=body.subject||'(No subject)';const p=document.createElement('pre');p.style.whiteSpace='pre-wrap';p.style.overflowWrap='anywhere';p.textContent=body.body?.contentType?.toLowerCase()==='text'?body.body.content:'This message cannot be displayed safely as text. Read it in Outlook.';const reply=document.createElement('button');reply.textContent='Prepare reply';reply.type='button';reply.addEventListener('click',()=>{const f=document.getElementById('deskEmailForm');f.elements.recipient.value=body.replyTo?.[0]?.emailAddress?.address||body.from?.emailAddress?.address||'';f.elements.subject.value=('Re: '+(body.subject||'')).slice(0,180);const to=[...(body.toRecipients||[]),...(body.ccRecipients||[])].map(x=>x.emailAddress.address.toLowerCase()).find(x=>aliases.includes(x));f.elements.from.value=to||'dispatch@harperloadboard.com';f.elements.message.value='';f.elements.message.focus();f.scrollIntoView({behavior:'smooth'});});detail.append(h,p,reply);}catch(e){if(version===epoch)sayError(e);}}
async function load(more=false){if(busy||!account)return;busy=true;controls();const version=epoch;state.textContent='Loading Harper mail…';try{if(!more){next=first;scanned=0;seen.clear();list.replaceChildren();detail.replaceChildren();}let pages=0;do{const data=await graph(next);if(version!==epoch)return;scanned+=data.value.length;for(const m of data.value){if(!isHarperMessage(m)||seen.has(m.id))continue;seen.add(m.id);const b=document.createElement('button');b.type='button';b.className='ghost-button';b.style.display='block';b.style.marginBottom='8px';b.textContent=[new Date(m.receivedDateTime).toLocaleString(),m.from?.emailAddress?.address,m.subject||'(No subject)'].join(' · ');b.addEventListener('click',()=>openMessage(m));list.append(b);}next=data['@odata.nextLink']||null;pages++;}while(next&&pages<5);state.textContent=seen.size+' Harper messages found among '+scanned+' recent mailbox messages. Includes Junk; select Load older to search further.';}catch(e){if(version===epoch)sayError(e);}finally{if(version===epoch){busy=false;controls();}}}
connect.addEventListener('click',async()=>{if(busy)return;busy=true;controls();const version=epoch;try{await init();const result=await app.loginPopup({scopes,loginHint:'wharper031@outlook.com',prompt:'select_account'});if(version!==epoch){await app.clearCache();return;}account=result.account;const me=await graph('https://graph.microsoft.com/v1.0/me?$select=mail,userPrincipalName');if(![me.mail,me.userPrincipalName,account.username].some(x=>String(x||'').toLowerCase()==='wharper031@outlook.com')){reset();await app.clearCache();throw new Error('Connect wharper031@outlook.com for the Harper inbox.');}busy=false;await load();}catch(e){if(version===epoch)sayError(e);}finally{busy=false;controls();}});
refresh.addEventListener('click',()=>load());older.addEventListener('click',()=>load(true));disconnect.addEventListener('click',async()=>{reset();await app?.clearCache();state.textContent='Disconnected from Outlook on this page.';});
async function visibility(){try{await admin();panel.hidden=false;}catch{reset();await app?.clearCache();panel.hidden=true;}}
window.addEventListener('alphaway:account-changed',()=>{reset();app?.clearCache();visibility();});
window.addEventListener('pagehide',()=>{reset();app?.clearCache();});
setInterval(()=>{if(account&&!busy)visibility();},30000);
visibility();controls();
