/* Device-local Harper planning tools. No external load feeds or customer billing. */
'use strict';
const M=HarperTools, $=id=>document.getElementById(id), STORE='harper-planning-v1';
let state={version:1,loads:[],favorites:[],blocked:[],alerts:[],trip:[],density:'default'};
const message=t=>{$('status').textContent=t;};
try{const saved=localStorage.getItem(STORE);if(saved)state=M.restore(JSON.parse(saved));}catch(e){message('Saved data could not be opened. Export or recover your backup before entering new data.');}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number.isFinite(n)?new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n):'Not achievable';
const uid=()=>crypto.randomUUID();
const fields=form=>Object.fromEntries(new FormData(form));
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));return true;}catch{message('Storage is full or unavailable. Changes are only in memory; export a backup now.');return false;}}
function tab(name){document.querySelectorAll('.tab').forEach(s=>s.hidden=s.id!==name);document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===name)));if(name==='documents')renderDocs();}
$('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b)tab(b.dataset.tab);});
function filter(){const f=fields($('filters'));return {...f,favorites:f.favorites==='on'};}
function metrics(el,items){el.innerHTML=items.map(([label,value,neg])=>`<div class="metric"><span>${esc(label)}</span><strong class="${neg?'negative':''}">${esc(value)}</strong></div>`).join('');}
function render(){
 const f=filter(), available=state.loads.filter(r=>M.matches(r,{},state.blocked)), rows=state.loads.filter(r=>M.matches(r,f,state.blocked,state.favorites));
 $('density').value=state.density;$('rows').dataset.density=state.density;
 $('count').textContent=`${rows.length} matches · ${available.filter(r=>!r.test).length} entered loads · ${available.filter(r=>r.test).length} TEST examples · no external live feed`;
 $('rows').innerHTML=rows.length?rows.map(r=>`<article class="load"><div><h3>${r.test?'<span class="test">TEST</span>':''}${esc(r.origin)} → ${esc(r.destination)}</h3><p>${esc(r.company)} · ${esc(r.equipment)} · Pickup ${esc(r.pickup)}</p><p>${r.miles.toLocaleString()} loaded miles · Source: ${esc(r.source)}</p><p>${esc(r.reference)}</p><div class="actions"><button data-action="favorite" data-id="${esc(r.id)}" aria-pressed="${state.favorites.includes(r.id)}">${state.favorites.includes(r.id)?'★ Saved':'☆ Favorite'}</button><button data-action="trip" data-id="${esc(r.id)}">Add to trip</button><button data-action="profit" data-id="${esc(r.id)}">Estimate profit</button><button data-action="returns" data-id="${esc(r.id)}">Find return loads</button><button class="secondary" data-action="block" data-id="${esc(r.id)}">Block company</button><button class="secondary" data-action="close" data-id="${esc(r.id)}">Mark closed</button></div></div><div><div class="amount">${money(r.rate)}</div><p>${money(r.rate/r.miles)}/loaded mile</p><p>Entered offer · confirm availability with source</p></div></article>`).join(''):'<div class="empty">No matching loads. Add your own load or use clearly labeled TEST examples to explore the tools.</div>';
 $('blocked').innerHTML=state.blocked.length?state.blocked.map((c,i)=>`<div class="item"><span>${esc(c)}</span><button data-unblock="${i}">Unblock</button></div>`).join(''):'No blocked companies.';
 $('closed').innerHTML=state.loads.filter(r=>r.status==='closed').map(r=>`<div class="item"><span>${esc(r.company)} · ${esc(r.origin)} → ${esc(r.destination)}</span><button data-reopen="${esc(r.id)}">Reopen</button></div>`).join('')||'No closed loads.';
 const counts=new Map();available.forEach(r=>{const label=r.origin+(r.test?' (TEST)':'');counts.set(label,(counts.get(label)||0)+1);});
 $('densityList').innerHTML=[...counts].sort((a,b)=>b[1]-a[1]).map(([k,n])=>`<div class="item"><span>${esc(k)}</span><strong>${n}</strong></div>`).join('')||'Add loads to see availability.';
 $('alertCount').textContent=`(${state.alerts.length})`;
 $('alerts').innerHTML=state.alerts.map(a=>{const match=state.loads.filter(r=>M.matches(r,a,state.blocked));const fresh=match.filter(r=>!a.seen.includes(r.id));return `<div class="item"><span>${esc(a.name)}<br><small>${match.length} matches · ${fresh.length} new since last review</small></span><div><button data-view-alert="${esc(a.id)}">View</button> <button class="secondary" data-delete-alert="${esc(a.id)}">Remove</button></div></div>`;}).join('')||'Save a search to track matching loads here.';
 renderTrip();
}
$('filters').addEventListener('input',render);$('filters').addEventListener('reset',()=>setTimeout(render,0));
$('density').addEventListener('change',()=>{state.density=$('density').value;save();render();});
$('addLoad').addEventListener('submit',e=>{e.preventDefault();try{if(state.loads.length>=2000)throw new Error('Export your workspace; this preview supports 2,000 loads.');const f=fields(e.target);state.loads.push(M.load({...f,id:uid(),test:f.test==='on'}));save();render();e.target.reset();message('Load added. Saved search matches have been updated.');}catch(err){message(err.message);}});
$('saveAlert').addEventListener('click',()=>{if(state.alerts.length>=50)return message('This preview supports 50 saved searches.');const f=filter();delete f.favorites;const name=[f.origin||'Any origin',f.destination||'Any destination',f.equipment||'Any equipment'].join(' → ');state.alerts.push({...f,id:uid(),name,seen:state.loads.filter(r=>M.matches(r,f,state.blocked)).map(r=>r.id)});save();render();message('Search saved. New matching loads will appear in Saved search alerts.');});
$('rows').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const r=state.loads.find(r=>r.id===b.dataset.id);if(!r)return;switch(b.dataset.action){case 'favorite':state.favorites=state.favorites.includes(r.id)?state.favorites.filter(id=>id!==r.id):[...state.favorites,r.id];break;case 'block':if(!state.blocked.some(c=>M.key(c)===M.key(r.company)))state.blocked.push(r.company);break;case 'close':r.status='closed';break;case 'trip':if(!state.trip.includes(r.id))state.trip.push(r.id);message('Added to Trip planner. This does not reserve the load.');break;case 'profit':$('calculator').elements.rate.value=r.rate;$('calculator').elements.miles.value=r.miles;tab('profit');$('profitResult').replaceChildren();message('Load revenue and mileage copied. Enter your remaining trip costs.');return;case 'returns':$('filters').reset();$('filters').elements.origin.value=r.destination;$('filters').elements.date.value=r.pickup;message('Showing pickups from this destination on or after this pickup date. Verify delivery time, appointments and equipment yourself.');break;}save();render();});
$('blocked').addEventListener('click',e=>{const b=e.target.closest('[data-unblock]');if(b){state.blocked.splice(Number(b.dataset.unblock),1);save();render();}});
$('closed').addEventListener('click',e=>{const b=e.target.closest('[data-reopen]');if(b){const r=state.loads.find(r=>r.id===b.dataset.reopen);if(r)r.status='available';save();render();}});
$('alerts').addEventListener('click',e=>{const del=e.target.closest('[data-delete-alert]'),view=e.target.closest('[data-view-alert]');if(del)state.alerts=state.alerts.filter(a=>a.id!==del.dataset.deleteAlert);if(view){const a=state.alerts.find(a=>a.id===view.dataset.viewAlert);if(a){$('filters').reset();for(const k of ['origin','destination','equipment','minimum','date'])$('filters').elements[k].value=a[k]||'';a.seen=state.loads.filter(r=>M.matches(r,a,state.blocked)).map(r=>r.id);}}save();render();});
$('calculator').addEventListener('submit',e=>{e.preventDefault();try{const p=M.profit(fields(e.target));metrics($('profitResult'),[['Estimated net',money(p.net),p.net<0],['Net per trip day',money(p.perDay),p.perDay<0],['All-mile revenue',money(p.perMile)],['Fuel estimate',money(p.fuelCost)],['Dispatch fee',money(p.dispatchCost)],['Break-even revenue',money(p.breakEven)]]);}catch(err){message(err.message);}});
function renderTrip(){const rows=state.trip.map(id=>state.loads.find(r=>r.id===id)).filter(Boolean);$('tripRows').innerHTML=rows.map((r,i)=>`<li class="item"><span>${r.test?'TEST · ':''}${esc(r.origin)} → ${esc(r.destination)}<br><small>${esc(r.pickup)} · ${money(r.rate)} · ${r.status}${state.blocked.some(c=>M.key(c)===M.key(r.company))?' · BLOCKED COMPANY':''}</small></span><div><button data-up="${i}" ${i===0?'disabled':''}>Move up</button> <button data-remove-trip="${esc(r.id)}" class="secondary">Remove</button></div></li>`).join('')||'<li class="empty">Add loads from the workspace to plan a trip.</li>';$('tripResult').replaceChildren();}
$('tripRows').addEventListener('click',e=>{const up=e.target.closest('[data-up]'),remove=e.target.closest('[data-remove-trip]');if(up){const i=Number(up.dataset.up);if(i>0)[state.trip[i-1],state.trip[i]]=[state.trip[i],state.trip[i-1]];}if(remove)state.trip=state.trip.filter(id=>id!==remove.dataset.removeTrip);save();renderTrip();});
$('tripForm').addEventListener('submit',e=>{e.preventDefault();try{const rows=state.trip.map(id=>state.loads.find(r=>r.id===id)).filter(Boolean);if(rows.some(r=>r.status!=='available'||state.blocked.some(c=>M.key(c)===M.key(r.company))))throw new Error('Remove closed loads or loads from blocked companies before calculating.');if(rows.some(r=>r.test)&&rows.some(r=>!r.test))throw new Error('Keep TEST examples and real loads in separate trips.');const p=M.trip(rows,fields(e.target).gaps);metrics($('tripResult'),[['Planned revenue',money(p.rate)],['Loaded miles',p.loaded.toLocaleString()],['Total miles',p.totalMiles.toLocaleString()],['All-mile revenue',money(p.perMile)]]);}catch(err){message(err.message);}});
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('export').addEventListener('click',()=>{download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'harper-workspace.json');message('Workspace exported. Documents are separate: download them from Documents.');});
$('import').addEventListener('change',async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>5000000)throw new Error('Workspace import limit is 5 MB.');const imported=M.restore(JSON.parse(await file.text()));if(!confirm('Replace the current load workspace with this backup? Documents stay unchanged. Export your current workspace first if needed.'))return;state=imported;save();render();message('Workspace imported and validated.');}catch(err){message(err.message);}finally{e.target.value='';}});
$('examples').addEventListener('click',()=>{if(state.loads.some(r=>r.id==='harper-test-1'))return message('TEST examples already exist.');const date=new Date().toISOString().slice(0,10);const examples=[['Colorado Springs, CO','Dallas, TX',2500,750],['Dallas, TX','Denver, CO',2300,790],['Denver, CO','Phoenix, AZ',2100,860]];examples.forEach((r,i)=>state.loads.push(M.load({id:`harper-test-${i+1}`,company:'TEST Example Freight',origin:r[0],destination:r[1],rate:r[2],miles:r[3],pickup:date,equipment:'Dry Van',source:'Fictional example — not bookable',test:true})));save();render();message('Added three fictional TEST examples. No real freight has been posted.');});
let dbPromise;
function db(){return dbPromise ||= new Promise((resolve,reject)=>{const req=indexedDB.open('harper-documents-v1',1);req.onupgradeneeded=()=>req.result.createObjectStore('documents',{keyPath:'id'});req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(new Error('Document storage is unavailable in this browser.'));});}
async function documentOp(mode,operation){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('documents',mode),req=operation(tx.objectStore('documents'));tx.oncomplete=()=>resolve(req.result);tx.onerror=()=>reject(new Error('Document could not be saved. Check browser storage space.'));tx.onabort=()=>reject(new Error('Document storage operation was cancelled.'));});}
async function renderDocs(){try{const docs=await documentOp('readonly',s=>s.getAll());$('documentList').innerHTML=docs.map(d=>`<div class="item"><span>${esc(d.name)}<br><small>${esc(d.reference)} · ${Math.ceil(d.blob.size/1024)} KB · stored on this device</small></span><button data-download-doc="${esc(d.id)}">Download</button></div>`).join('')||'<p>No documents stored on this device.</p>';}catch(err){message(err.message);}}
$('documentForm').addEventListener('submit',async e=>{e.preventDefault();const file=$('documentFile').files[0];if(!file)return;if(file.size>10*1024*1024)return message('Choose a file smaller than 10 MB.');if(!/\.(pdf|png|jpe?g|txt|csv)$/i.test(file.name))return message('Supported documents: PDF, PNG, JPG, TXT, CSV.');try{await documentOp('readwrite',s=>s.add({id:uid(),name:file.name,reference:$('documentRef').value,blob:file}));e.target.reset();await renderDocs();message('Document saved on this device. Keep your original backup.');}catch(err){message(err.message);}});
$('documentList').addEventListener('click',async e=>{const b=e.target.closest('[data-download-doc]');if(!b)return;try{const d=await documentOp('readonly',s=>s.get(b.dataset.downloadDoc));if(d)download(d.blob,d.name);}catch(err){message(err.message);}});
render();
